# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('chat', '0002_auto_20170927_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
