# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
