# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20171022_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='author',
            new_name='sender',
        ),
    ]
